ControlT/ControlT.Mvc/Controllers/CajasController.cs
namespace ControlT.Mvc.Controllers
{
    using System.Web.Mvc;
    using EF;
    using Models;

    public class CajasController : Controller
    {
        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult Cajas()
        {
            var uow = new ControlTContext();
            var model = new CajasModel(uow.Cajas);
            return this.PartialView(model);            
        }

        public ActionResult Create()
        {
            return this.PartialView();
        }

        [HttpPost]
        public ActionResult Create(CajaModel caja)
        {
            var uow = new ControlTContext();

            var nueva = new Caja
            {
                Nombre = caja.Nombre
            };

            uow.Cajas.Add(nueva);
            uow.SaveChanges();
            var result = new { success = true };
            return Json(result);
        }
    }
}

ControlT/ControlT.Mvc/Views/Cajas/Cajas.cshtml
@model ControlT.Mvc.Models.CajasModel

<thead>
    <tr>
        <th>Caja</th>
    </tr>
</thead>
<tbody>
    @foreach (var caja in @Model.Cajas)
    {
        <tr>
            <td>@caja.Nombre</td>
        </tr>
    }
</tbody>           

ControlT/ControlT.Mvc/Views/Cajas/Create.cshtml
@model ControlT.Mvc.Models.CajaModel

@{
    ViewBag.Title = "Nueva Caja";
}
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Caja</h3>
    </div>
    @using (Html.BeginForm("Create", "Cajas", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="modal-body">
            <div class="form-group">
                <div class="col-xs-3">
                    <label for="Nombre" class="control-label">Nombre:</label>
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(x => x.Nombre, new { @class = "col-xs-12 form-control" })
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" value="Cancelar">Cancelar</button>
            <button class="btn btn-primary" type="submit" value="Guardar">Guardar</button>
        </div>
    }
</div>

ControlT/ControlT.Mvc/Views/Cajas/Index.cshtml
@{
    ViewBag.Title = "Cajas";
}

<div id='dialogDiv' class='modal'>
    <div class="modal-dialog" id='dialogContent'></div>
</div>

<div class="page-header" id="banner">
    <div class="row">
        <h1 class="col-xs-12">Cajas</h1>
    </div>
</div>

<div id="datos">
    <table class="col-xs-12 table table-striped table-hover"></table>
</div>
<div class="col-xs-12 text-right">
    <a href="Cajas/Create" id="btnCreate" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span></a>
</div>
<script src="~/Scripts/modal.js"></script>
<script>
    $(document).ready(function () {
        $("#btnCajas").addClass("active");
        cargarGrilla();
        btnModal('btnCreate', cargarGrilla);
    });

    function cargarGrilla() {
        $("#datos").find("table").load("Cajas/Cajas", function () {
            $("#datos").fadeIn();
        });
    }    
    

</script>