ControlT/ControlT.Mvc/Controllers/MovimientosController.cs
namespace ControlT.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Web.Mvc;
    using EF;
    using Models;
    using Utils;

    public class MovimientosController : Controller
    {
        public ActionResult Index()
        {
            var uow = new ControlTContext();

            var cajas = new List<SelectListItem>();
            var selected = true;

            foreach (var caja in uow.Cajas.ToArray())
            {
                var li = new SelectListItem
                {
                    Text = caja.Nombre,
                    Value = caja.CajaID.ToString(CultureInfo.InvariantCulture),
                    Selected = selected
                };
                cajas.Add(li);
                selected = false;
            }

            var model = new MovimientosModel(cajas);
            return View(model);
        }

        public ActionResult Movimientos(int idCaja, string fechaDesde, string fechaHasta)
        {
            var uow = new ControlTContext();
            var fecDesde = fechaDesde.ToDate();
            var fecHasta = fechaHasta.ToDate();

            var movimientosModel = new List<MovimientoModel>();

            var movimientosAnteriores = uow.Movimientos.Where(x => x.Caja.CajaID == idCaja && x.Fecha < fecDesde);
            var saldoAnterior = movimientosAnteriores.Any() ? movimientosAnteriores.Sum(x => x.Importe) : 0M;

            AddLineaSaldoAnteriorSiCorresponde(saldoAnterior, fecDesde, movimientosModel);
          
            var movimientos = uow.Movimientos.Where(x => x.Caja.CajaID == idCaja && x.Fecha >= fecDesde && x.Fecha <= fecHasta);
            AddLineas(movimientos, saldoAnterior, movimientosModel);

            return this.PartialView(movimientosModel);
        }

        public ActionResult Create()
        {
            var uow = new ControlTContext();

            var cajas = uow.Cajas.Select(x => new {x.Nombre, x.CajaID}).ToArray();
            this.ViewBag.Cajas = cajas.Select(x => new SelectListItem {Text = x.Nombre, Value = x.CajaID.ToString(CultureInfo.InvariantCulture)}).ToArray();

            return this.PartialView();
        }

        [HttpPost]
        public ActionResult Create(NuevoMovimientoModel movimiento)
        {
            var uow = new ControlTContext();

            var importe = movimiento.Importe;
            if (movimiento.TipoMovimiento == "Egreso")
                importe *= -1;

            var nuevo = new Movimiento
            {
                CajaID = movimiento.CajaID,
                Importe = importe,
                Concepto = movimiento.Concepto,
                Fecha = movimiento.Fecha.ToDate(),
                EsExtraordinario = false
            };

            uow.Movimientos.Add(nuevo);
            uow.SaveChanges();
            var result = new {success = true};
            return Json(result);
        }

        private static void AddLineaSaldoAnteriorSiCorresponde(decimal saldoAnterior, DateTime fecDesde, ICollection<MovimientoModel> movimientosModel)
        {
            if (saldoAnterior <= 0) return;
            var movimientoModel = new MovimientoModel(fecDesde.AddDays(-1), saldoAnterior);
            movimientosModel.Add(movimientoModel);
        }
        private static void AddLineas(IEnumerable<Movimiento> movimientos, decimal saldo, ICollection<MovimientoModel> movimientosModel)
        {
            foreach (var movimiento in movimientos)
            {
                saldo += movimiento.Importe;
                var movimientoModel = new MovimientoModel(movimiento, saldo);
                movimientosModel.Add(movimientoModel);
            }
        }
    }
}

ControlT/ControlT.Mvc/Views/Movimientos/Create.cshtml
@model ControlT.Mvc.Models.NuevoMovimientoModel

@{
    ViewBag.Title = "Nuevo Movimiento";
}
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Movimiento</h3>
    </div>
    @using (Html.BeginForm("Create", "Movimientos", FormMethod.Post, new {@class = "form-horizontal"}))
    {
        <div class="modal-body">
            <div class="form-group">
                <div class="col-xs-3">
                    <label for="Fecha" class="control-label">Fecha:</label>
                </div>
                <div class="col-xs-3">
                    @Html.TextBoxFor(x => x.Fecha, new { @class = "col-xs-12 form-control"})                    
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    <label for="CajaID" class="control-label">Caja:</label>
                </div>
                <div class="col-xs-9">
                    @Html.DropDownListFor(x => x.CajaID, (IEnumerable<SelectListItem>) ViewBag.Cajas, new { @class = "col-xs-12 form-control"})
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    <label for="Importe" class="control-label">Importe:</label>
                </div>
                <div class="col-xs-9">
                    <div class="row">
                        <div class="col-xs-6">
                            @Html.TextBoxFor(x => x.Importe, new { @class = "text-right form-control" })
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-xs-6">
                            @Html.RadioButtonFor(x => x.TipoMovimiento, "Ingreso", new { @id = "Ingreso", value = "Ingreso" })
                            <label for="Ingreso" class="control-label">Ingreso</label>
                        </div>
                        <div class="col-xs-6">
                            @Html.RadioButtonFor(x => x.TipoMovimiento, "Egreso", new { @id = "Egreso", value = "Egreso" })
                            <label for="Egreso" class="control-label">Egreso</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    <label for="Concepto" class="control-label">Concepto:</label>
                </div>
                <div class="col-xs-9">
                    @Html.TextBoxFor(x => x.Concepto, null, new { @class = "col-xs-12 form-control" })
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true" value="Cancelar">Cancelar</button>
            <button class="btn btn-primary" type="submit" value="Guardar">Guardar</button>
        </div>
    }
</div>
<script>
    $(document).ready(function () {
        $("#Fecha").datepicker({ dateFormat: 'dd-mm-yy' });
    });
</script>

ControlT/ControlT.Mvc/Views/Movimientos/Index.cshtml
@model ControlT.Mvc.Models.MovimientosModel

@{
    ViewBag.Title = "Movimientos de Caja";
}

<div id='dialogDiv' class='modal'>
    <div class="modal-dialog" id='dialogContent'></div>
</div>

<div class="page-header" id="banner">
    <div class="row">
        <h1 class="col-xs-12">Movimientos de Caja</h1>
    </div>
</div>
<div id="filtros">
    <h2 class="col-xs-12">Filtros</h2>
    <div class="col-xs-6">
        <form class="form-horizontal">
            <fieldset>
                <div class="form-group">
                    <label class="col-xs-2 control-label">Caja</label>
                    <div class="col-xs-6">@Html.DropDownList("caja", @Model.Cajas, new { @class = "form-control" })</div>
                </div>
                <div class="form-group">
                    <label class="col-xs-2 control-label">Periodo</label>
                    <div class="col-xs-4">@Html.TextBox("fechaDesde", DateTime.Today.AddMonths(-1).ToShortDateString(), new { @class = "fecha form-control" })</div>
                    <label class="col-lg-1 control-label"> - </label>
                    <div class="col-xs-4">@Html.TextBox("fechaHasta", DateTime.Today.ToShortDateString(), new { @class = "fecha form-control" })</div>
                </div>
            </fieldset>
            <div class="col-xs-12 text-right">
                <button id="consultar" class="btn btn-primary">Consultar</button>
            </div>
        </form>
    </div>
</div>
<button class="btn btn-primary col-xs-12" style="display: none" id="btnFiltrar">Filtrar <span class="glyphicon glyphicon-arrow-down"></span></button>

<h2 class="col-xs-12">Movimientos</h2>

<table class="table table-hover table-striped table-condensed col-xs-12" id="movimientos" style="display: none">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Concepto</th>
            <th class="text-right">Importe</th>
            <th class="text-right">Saldo</th>
            <th class="text-center">Modificar</th>
            <th class="text-center">Eliminar</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
<div class="col-xs-12 text-right">
    <a href="Movimientos/Create" id="btnCreate" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span></a>
</div>
<script src="~/Scripts/modal.js"></script>
<script>
    $(document).ready(function () {
        $("#btnMovimientos").addClass("active");
        $(".fecha").datepicker({ dateFormat: 'dd-mm-yy' });

        $("#movimientos").hide();

        cargarGrilla();

        $("#consultar").on("click", function (event) {
            event.preventDefault();
            $("#movimientos").fadeOut(function () {
                cargarGrilla();
            });
        });

        $("#btnFiltrar").on("click", function (event) {
            event.preventDefault();
            $(this).fadeOut();
            $("#filtros").slideDown();
        });

        btnModal('btnCreate', cargarGrilla);
    });

    function cargarGrilla() {
        var idCaja = $("#caja").val();
        var fechaDesde = $("#fechaDesde").val().replace(/\//g, "-");
        var fechaHasta = $("#fechaHasta").val().replace(/\//g, "-");
        $("#movimientos").find("tbody").load("Movimientos/Movimientos?idCaja=" + idCaja + "&fechaDesde=" + fechaDesde + "&fechaHasta=" + fechaHasta, function () {
            $("#movimientos").fadeIn();
            $("#filtros").slideUp();
            $("#btnFiltrar").fadeIn();
        });
    }
</script>

ControlT/ControlT.Mvc/Views/Movimientos/Movimientos.cshtml
@model IEnumerable<ControlT.Mvc.Models.MovimientoModel>
 
@foreach(var movimiento in @Model)
{
    <tr class="@movimiento.CssClass">
        <td>@movimiento.Fecha.ToShortDateString()</td>
        <td>@movimiento.Concepto</td>
        <td class="text-right">@movimiento.Importe.ToString("N2")</td>
        <td class="text-right">@movimiento.Saldo.ToString("N2")</td>
        <td class="text-center">
            @if (movimiento.EsEditable)
            {
                <button class="btn btn-info"><span class="glyphicon glyphicon-edit"></span></button>
            }
        </td>
        <td class="text-center">
            @if (movimiento.EsEditable)
            {
                <button class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
            }
        </td>
    </tr>
}